### ISSUE TITLE
Seems not working

### ISSUE THREAD

**Issue by angerangel** [PaulMcClernan/LiveCodeStuff#1]
Hi,
I tried to use it, but clicking on it just blink it. 
I use livecode 9 dp3.
How can user click on it and change the **amountOfStars**?

**Comment by PaulMcClernan** [comment]
You must script your own functionality, however there is a default script included that shows one way that it can be used. To use the default script: Edit the script of the widget, it should be pre-filled in with the script, and then save the script and then default script will be compiled/activated.
